### ISSUE TITLE
Molecular data not displayed for HCMI/HCM-CSHL-0065-C20

### ISSUE THREAD

**Issue by mauroz77** [PDCMFinder/pdcm-etl#218]
![Screenshot 2023-01-30 at 10.21.26.png](https://images.zenhubusercontent.com/5e26fc6d88046303e1f447a3/eb931803-7c16-4cd6-b3cb-be40433ac747)

![Screenshot 2023-01-30 at 10.21.08.png](https://images.zenhubusercontent.com/5e26fc6d88046303e1f447a3/f2258392-1521-4d15-93ee-062b8183999d)

Note: Table available_molecular_data_columns does not have data for HCMI.

**Comment by mauroz77** [comment]
Tsv files from the same type should all have the same columns in the same order. For mutation data there are 3 different sets of columns, order:

`sample_id	symbol	biotype	coding_sequence_change	variant_class	codon_change	amino_acid_change	consequence	functional_prediction	read_depth	allele_frequency	chromosome	seq_start_position	ref_allele	alt_allele	ucsc_gene_id	ncbi_gene_id	ncbi_transcript_id	ensembl_gene_id	ensembl_transcript_id	variation_id	platform_id	strand
`
`sample_id	symbol	biotype	coding_sequence_change	variant_class	codon_change	amino_acid_change	consequence	functional_prediction	read_depth	allele_frequency	chromosome	seq_start_position	strand	ref_allele	alt_allele	ucsc_gene_id	ncbi_gene_id	ncbi_transcript_id	ensembl_gene_id	ensembl_transcript_id	variation_id	platform_id
`
`sample_id	symbol	biotype	coding_sequence_change	variant_class	codon_change	amino_acid_change	consequence	functional_prediction	strand	read_depth	allele_frequency	chromosome	seq_start_position	ref_allele	alt_allele	ucsc_gene_id	ncbi_gene_id	ncbi_transcript_id	ensembl_gene_id	ensembl_transcript_id	variation_id	platform_id
`

**Comment by Mandloi2309** [comment]
Data changes done

**Comment by mauroz77** [comment]
@zperova this is applied in dev/prod now
